name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Generate README file
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit README changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update generated README"
          file_pattern: README.md
